### ISSUE TITLE
npm @latest is pointing to an old version

### ISSUE THREAD

**Issue by tarek-eg** [MioQuispe/create-ic-app#15]
Hello,
Thanks for the great work.
I noticed that `latest` on npm is pointing at `0.1.7` and not to latest
https://www.npmjs.com/package/create-ic-app/v/0.0.9

**Comment by MioQuispe** [comment]
> Hello, Thanks for the great work. I noticed that `latest` on npm is pointing at `0.1.7` and not to latest https://www.npmjs.com/package/create-ic-app/v/0.0.9

Ah thanks, forgot to publish.
