### ISSUE TITLE
Error when running npx create-ic-app@latest

### ISSUE THREAD

**Issue by tarek-eg** [MioQuispe/create-ic-app#16]
Hey,
Looks like you published the dev branch instead of the main branch maybe?
I get error when I run `npx create-ic-app@latest`
```
Error: ENOENT: no such file or directory, scandir /node_modules/create-ic-app/langs'
```

It's looking for the `lang` directory but it's not there on main, however I found the last PR for internationalization is merged to dev instead which had the lang dir.

**Comment by MioQuispe** [comment]
> Hey, Looks like you published the dev branch instead of the main branch maybe? I get error when I run `npx create-ic-app@latest`
> 
> ```
> Error: ENOENT: no such file or directory, scandir /node_modules/create-ic-app/langs'
> ```
> 
> It's looking for the `lang` directory but it's not there on main, however I found the last PR for internationalization is merged to dev instead which had the lang dir.

Ah shit. sorry, thanks for reporting. fixed
