### ISSUE TITLE
DFX latest? I have 0.10.0

### ISSUE THREAD

**Issue by AshtonEngberg** [MioQuispe/create-ic-app#21]
The guide says 0.8.2 as the latest, though I have 0.10.0. After I `npm install` `dfx start` and then...
```
dfx deploy
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "default" is "rklht-iiaaa-aaaaa-aaaaa-cai"
Deploying all canisters.
Creating canisters...
Creating canister "assets"...
"assets" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Creating canister "counter"...
"counter" canister created with canister id: "ryjl3-tyaaa-aaaaa-aaaba-cai"
Building canisters...
Building frontend...
Error: The post-build step failed for canister 'rrkah-fqaaa-aaaaa-aaaaq-cai' (assets) with an embedded error: The command '"npm" "run" "build"' failed with exit status 'exit status: 1'.
Stdout:

> dapp.icp@0.0.0 build
> vite build

vite v2.9.13 building for production...
transforming...
✓ 394 modules transformed.

Stderr:
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
'PipeArrayBuffer' is not exported by node_modules/@dfinity/candid/lib/esm/index.js, imported by node_modules/@dfinity/agent/lib/esm/canisterStatus/index.js
file: ~/node_modules/@dfinity/agent/lib/esm/canisterStatus/index.js:2:20
1: /** @module CanisterStatus */
2: import { lebDecode, PipeArrayBuffer } from '@dfinity/candid';
                       ^
3: import { Principal } from '@dfinity/principal';
4: import { Cbor, Certificate, toHex } from '..';
error during build:
Error: 'PipeArrayBuffer' is not exported by node_modules/@dfinity/candid/lib/esm/index.js, imported by node_modules/@dfinity/agent/lib/esm/canisterStatus/index.js
    at error (~/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (~/node_modules/rollup/dist/shared/rollup.js:12555:16)
    at Module.traceVariable (~/node_modules/rollup/dist/shared/rollup.js:12914:29)
    at ModuleScope.findVariable (~/node_modules/rollup/dist/shared/rollup.js:11566:39)
    at ReturnValueScope.findVariable (~/node_modules/rollup/dist/shared/rollup.js:6486:38)
    at ChildScope.findVariable (~/node_modules/rollup/dist/shared/rollup.js:6486:38)
    at Identifier.bind (~/node_modules/rollup/dist/shared/rollup.js:7553:40)
    at NewExpression.bind (~/node_modules/rollup/dist/shared/rollup.js:5383:23)
    at CallExpression.bind (~/node_modules/rollup/dist/shared/rollup.js:5379:73)
    at CallExpression.bind (~/node_modules/rollup/dist/shared/rollup.js:9049:15)
```
To fix what is recommended? I'm guessing it is a mismatch due to dfx versions, but is not 0.10.0 the latest?

**Comment by MioQuispe** [comment]
> The guide says 0.8.2 as the latest, though I have 0.10.0. After I `npm install` `dfx start` and then...
> 
> ```
> dfx deploy
> Creating a wallet canister on the local network.
> The wallet canister on the "local" network for user "default" is "rklht-iiaaa-aaaaa-aaaaa-cai"
> Deploying all canisters.
> Creating canisters...
> Creating canister "assets"...
> "assets" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
> Creating canister "counter"...
> "counter" canister created with canister id: "ryjl3-tyaaa-aaaaa-aaaba-cai"
> Building canisters...
> Building frontend...
> Error: The post-build step failed for canister 'rrkah-fqaaa-aaaaa-aaaaq-cai' (assets) with an embedded error: The command '"npm" "run" "build"' failed with exit status 'exit status: 1'.
> Stdout:
> 
> > dapp.icp@0.0.0 build
> > vite build
> 
> vite v2.9.13 building for production...
> transforming...
> ✓ 394 modules transformed.
> 
> Stderr:
> Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
> Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
> 'PipeArrayBuffer' is not exported by node_modules/@dfinity/candid/lib/esm/index.js, imported by node_modules/@dfinity/agent/lib/esm/canisterStatus/index.js
> file: ~/node_modules/@dfinity/agent/lib/esm/canisterStatus/index.js:2:20
> 1: /** @module CanisterStatus */
> 2: import { lebDecode, PipeArrayBuffer } from '@dfinity/candid';
>                        ^
> 3: import { Principal } from '@dfinity/principal';
> 4: import { Cbor, Certificate, toHex } from '..';
> error during build:
> Error: 'PipeArrayBuffer' is not exported by node_modules/@dfinity/candid/lib/esm/index.js, imported by node_modules/@dfinity/agent/lib/esm/canisterStatus/index.js
>     at error (~/node_modules/rollup/dist/shared/rollup.js:198:30)
>     at Module.error (~/node_modules/rollup/dist/shared/rollup.js:12555:16)
>     at Module.traceVariable (~/node_modules/rollup/dist/shared/rollup.js:12914:29)
>     at ModuleScope.findVariable (~/node_modules/rollup/dist/shared/rollup.js:11566:39)
>     at ReturnValueScope.findVariable (~/node_modules/rollup/dist/shared/rollup.js:6486:38)
>     at ChildScope.findVariable (~/node_modules/rollup/dist/shared/rollup.js:6486:38)
>     at Identifier.bind (~/node_modules/rollup/dist/shared/rollup.js:7553:40)
>     at NewExpression.bind (~/node_modules/rollup/dist/shared/rollup.js:5383:23)
>     at CallExpression.bind (~/node_modules/rollup/dist/shared/rollup.js:5379:73)
>     at CallExpression.bind (~/node_modules/rollup/dist/shared/rollup.js:9049:15)
> ```
> 
> To fix what is recommended? I'm guessing it is a mismatch due to dfx versions, but is not 0.10.0 the latest?

Hey I had forgotten to update the README, sorry about that. Im running 0.9.3 on my machine, but will try with 0.10.0 if I get the same issue. Which framework did you select btw?

**Comment by MioQuispe** [comment]
All templates worked without issue for me. Tried with both dfx 0.9.3 & 0.10.1

**Comment by AshtonEngberg** [comment]
Was using react/js. Tried it again, had to install vite, but it did work. Thanks again!
