### ISSUE TITLE
Error on dfx build

### ISSUE THREAD

**Issue by chiester** [MioQuispe/create-ic-app#5]
```
failed to load config from /site/vite.config.ts
error during build:
Error: Not supported
```

Any idea why this is happening?

**Comment by chiester** [comment]
I switch from node `12.16.1` to `14.17.0` and I think that fixed it.

**Comment by MioQuispe** [comment]
> I switch from node `12.16.1` to `14.17.0` and I think that fixed it.

Hey! Yeah sorry about that, I will add this requirement to the readme. There was some issue I can't remember that required upgrading, since I was using v12 too before. Is it working ok for you now?

**Comment by chiester** [comment]
Yes, it is working. Thank you for this project! It definitely accelerated my learning about ICP.

Maybe this is a separate issue, or not an issue at all, but any idea why it makes so many requests to do the counter increment? This is a shot of my console: <img width="208" alt="Screen Shot 2021-06-01 at 9 46 12 PM" src="https://user-images.githubusercontent.com/3964828/120411672-2f505e80-c323-11eb-97e0-fd2a73ddda7d.png">

**Comment by MioQuispe** [comment]
> Yes, it is working. Thank you for this project! It definitely accelerated my learning about ICP.
> 
> Maybe this is a separate issue, or not an issue at all, but any idea why it makes so many requests to do the counter increment? This is a shot of my console: <img alt="Screen Shot 2021-06-01 at 9 46 12 PM" width="208" src="https://user-images.githubusercontent.com/3964828/120411672-2f505e80-c323-11eb-97e0-fd2a73ddda7d.png">

I guess its getting the status of the update call:
https://sdk.dfinity.org/docs/interface-spec/index.html#http-call-overview

Tho, the last query should be unnecessary if you architect your app well. This is just quickly hacked together to get you going.
